events {}

http {
    upstream auth {
        server auth_service:8000;
    }
    upstream attendance {
        server attendance_service:8000;
    }
    upstream ai {
        server ai_service:8000;
    }
    upstream dashboard {
        server dashboard_service:8000;
    }

    server {
        listen 80;

        location /api/auth/ {
            proxy_pass http://auth/;
        }
        location /api/attendance/ {
            proxy_pass http://attendance/;
        }
        location /api/ai/ {
            proxy_pass http://ai/;
        }
        location /api/dashboard/ {
            proxy_pass http://dashboard/;
        }
    }
}
